// Code generated by mockery v2.42.0. DO NOT EDIT.

package domain

import mock "github.com/stretchr/testify/mock"

// MockEncrypter is an autogenerated mock type for the Encrypter type
type MockEncrypter struct {
	mock.Mock
}

type MockEncrypter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEncrypter) EXPECT() *MockEncrypter_Expecter {
	return &MockEncrypter_Expecter{mock: &_m.Mock}
}

// Encrypt provides a mock function with given fields: input
func (_m *MockEncrypter) Encrypt(input string) (string, error) {
	ret := _m.Called(input)

	if len(ret) == 0 {
		panic("no return value specified for Encrypt")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (string, error)); ok {
		return rf(input)
	}
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEncrypter_Encrypt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Encrypt'
type MockEncrypter_Encrypt_Call struct {
	*mock.Call
}

// Encrypt is a helper method to define mock.On call
//   - input string
func (_e *MockEncrypter_Expecter) Encrypt(input interface{}) *MockEncrypter_Encrypt_Call {
	return &MockEncrypter_Encrypt_Call{Call: _e.mock.On("Encrypt", input)}
}

func (_c *MockEncrypter_Encrypt_Call) Run(run func(input string)) *MockEncrypter_Encrypt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockEncrypter_Encrypt_Call) Return(_a0 string, _a1 error) *MockEncrypter_Encrypt_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEncrypter_Encrypt_Call) RunAndReturn(run func(string) (string, error)) *MockEncrypter_Encrypt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEncrypter creates a new instance of MockEncrypter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEncrypter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEncrypter {
	mock := &MockEncrypter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
